# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rating_pb2 as rating__pb2


class RatingReviewServicerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddReview = channel.unary_unary(
                '/rating.RatingReviewServicer/AddReview',
                request_serializer=rating__pb2.Review.SerializeToString,
                response_deserializer=rating__pb2.Review.FromString,
                )


class RatingReviewServicerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RatingReviewServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddReview': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReview,
                    request_deserializer=rating__pb2.Review.FromString,
                    response_serializer=rating__pb2.Review.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rating.RatingReviewServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RatingReviewServicer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rating.RatingReviewServicer/AddReview',
            rating__pb2.Review.SerializeToString,
            rating__pb2.Review.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
