# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rating.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crating.proto\x12\x06rating\"<\n\x06Review\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x05\x12\x0e\n\x06review\x18\x03 \x01(\t2E\n\x14RatingReviewServicer\x12-\n\tAddReview\x12\x0e.rating.Review\x1a\x0e.rating.Review\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rating_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REVIEW._serialized_start=24
  _REVIEW._serialized_end=84
  _RATINGREVIEWSERVICER._serialized_start=86
  _RATINGREVIEWSERVICER._serialized_end=155
# @@protoc_insertion_point(module_scope)
